// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, user_id, url, name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, url, name
`

type CreateFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Url    string
	Name   string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Name,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Name,
	)
	return i, err
}
