// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, user_id, url, name)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, url, name, created_at, last_fetched_at
`

type CreateFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Url    string
	Name   string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.UserID,
		arg.Url,
		arg.Name,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Name,
		&i.CreatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}

const findFeedByUrl = `-- name: FindFeedByUrl :one
SELECT id, user_id, url, name, created_at, last_fetched_at FROM feeds WHERE url = $1 LIMIT 1
`

func (q *Queries) FindFeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, findFeedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Name,
		&i.CreatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT feeds.id AS feed_id, users.name as user_name, feeds.name as feed_name, feeds.url as feed_url FROM feeds
INNER JOIN users on feeds.user_id = users.id
ORDER BY feeds.name ASC
`

type GetFeedsRow struct {
	FeedID   uuid.UUID
	UserName string
	FeedName string
	FeedUrl  string
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(
			&i.FeedID,
			&i.UserName,
			&i.FeedName,
			&i.FeedUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
