-- +goose up
CREATE TABLE posts (
  id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
  feed_id UUID NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
  title VARCHAR(150) NOT NULL,
  url VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +goose down
DROP TABLE posts;
